--RETORNA O CÓDIGO DAS SALAS QUE ESTÃO ATRIBUÍDAS A MAIS DE TRÊS TURMAS OU MATERIAS (GROUP BY/HAVING)
--OBS: isso é útil para identificar salas que podem estar sobrecarregadas com muitas atividades.
SELECT CODIGO_SALA
FROM POSSUI
GROUP BY CODIGO_SALA
HAVING COUNT(*) > 3

--RETORNA OS NOMES DOS PROFESSORES E OS NOMES DAS MATERIAS QUE ELES ENSINAM PARA OITAVA SÉRIE (JUNÇÃO INTERNA)
SELECT P.NOME, M.NOME AS MATERIA
FROM PROFESSOR P JOIN ENSINA E ON P.MATRICULA = E.MATRICULA JOIN MATERIA M ON M.CODIGO = E.CODIGO
WHERE SERIE = '8'

--RETORNA SALA DE AULA QUE NÃO POSSUI NENHUMA TURMA/MATERIA ATRIBUIDA. OU SEJA, SALAS DE AULA SEM NENHUMA AULA ATRIBUIDA (JUNÇÃO EXTERNA)
SELECT S.CODIGO, S.CAPACIDADE, S.TIPO_SALA
FROM SALA S LEFT JOIN POSSUI P ON S.CODIGO = P.CODIGO_SALA
WHERE P.CODIGO_TURMA IS NULL;

--RETORNA O NOME DO(S) PROFESSOR(ES) CUJA DATA DE NASCIMENTO É A MAIS ANTIGA ENTRE TODOS OS PROFESSORES CADASTRADOS (SUBCONSULTA ESCALAR)
SELECT NOME
FROM PROFESSOR
WHERE NASCIMENTO = (SELECT MIN(NASCIMENTO)
    FROM PROFESSOR);

--RETORNA OS CÓDIGOS DAS TURMAS QUE POSSUEM O MESMO NOME E ANO QUE A TURMA 1 (SUBCONSULTA LINHA)
SELECT CODIGO
FROM TURMA T
WHERE (T.ANO, T.NOME) = (SELECT T2.ANO, T2.NOME 
    FROM TURMA T2 
    WHERE T2.CODIGO = 1)
AND T.CODIGO <> 1;

--RETORNA AS MATRÍCULAS DOS PROFESSORES QUE JÁ RECEBERAM SALÁRIOS SUPERIORES A 3000 REAIS (SUBCONSULTA DO TIPO TABELA)
SELECT DISTINCT MATRICULA_PROFESSOR
FROM RECEBE
WHERE CODIGO_SALARIO IN (SELECT CODIGO
    	FROM SALARIO_PROFESSORES
	WHERE VALOR > 3000)

--RETORNA PROFESSORES QUE RECEBERAM O BÔNUS 1 (SEMI JOIN)
SELECT P.NOME AS NOME_PROFESSOR
FROM PROFESSOR P
WHERE EXISTS (
    SELECT 1
    FROM RECEBE R
    WHERE P.MATRICULA = R.MATRICULA_PROFESSOR
    AND R.CODIGO_BONUS = 1
);

--RETORNA PROFESSORES QUE NUNCA ENSINARAM UMA MATÉRIA (ANTI JOIN)
SELECT P.NOME AS NOME_PROFESSOR
FROM PROFESSOR P
WHERE NOT EXISTS (
    SELECT 1
    FROM ENSINA E
    WHERE P.MATRICULA = E.MATRICULA
);

-- RETORNA O NOME DAS PESSOAS QUE ESTÃO CADASTRADAS NAS INSTITUIÇÕES?
SELECT NOME
FROM PROFESSOR
UNION
SELECT NOME
FROM ALUNO

